Wild-Deer/Controllers/CacheController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Distributed;
using System.Text.Json;
using Wild_Deer.Models;

namespace Wild_Deer.Controllers
{
    public class CacheController : Controller
    {
        static int flag = 0;
        private readonly WildDeerContext _db;
        private readonly IDistributedCache redis;
        public CacheController(WildDeerContext db,IDistributedCache redis)
        {
            _db = db;
            this.redis = redis;
        }
        [Authorize (Policy = "SignedInCustomer")]
        public IActionResult CachePlease(int ProductID)
        {
            var user = HttpContext.User;
            var nameClaim = user.Claims.FirstOrDefault(c => c.Type == "UserID")?.Value;
            string referrerUrl = HttpContext.Request.Headers["Referer"].ToString();
            Product TargerProduct = _db.Products.FirstOrDefault(p => p.ProductId == ProductID);
            string key = "AddedProductsByID:" + nameClaim;
            if(flag == 0)
            {
                List<Product> added_to_cart_products = new List<Product>();
                added_to_cart_products.Add(TargerProduct);
                redis.SetString(key, JsonSerializer.Serialize(added_to_cart_products), new DistributedCacheEntryOptions
                {
                    AbsoluteExpirationRelativeToNow = TimeSpan.FromDays(5)
                });




            }
            else
            {
                //get list from redis
                List<Product> PrevList = JsonSerializer.Deserialize<List<Product>>(redis.GetString(key));
                //add new member to list
                PrevList.Add(TargerProduct);
                //set to redis
                redis.SetString(key, JsonSerializer.Serialize(PrevList), new DistributedCacheEntryOptions
                {
                    AbsoluteExpirationRelativeToNow = TimeSpan.FromDays(5)
                });
            }

            List<Product> x = JsonSerializer.Deserialize<List<Product>>(redis.GetString(key));
            flag++;
            //return Redirect("/Detail/Detail/"+"?id="+ProductID);
            return Redirect(referrerUrl);
        }

    }
}

Wild-Deer/Controllers/DetailController.cs
using Wild_Deer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace Wild_Deer.Controllers
{
    public class DetailController : Controller
    {
        public int ProductID { get; set; }
        private readonly WildDeerContext _contaxt;
        public DetailController(WildDeerContext dbcontext)
        {
            this._contaxt = dbcontext;
        }
        public IActionResult Index()
        {

            return View();
        }
        public IActionResult Detail(int id)
        {
            Product TargerProduct = _contaxt.Products.FirstOrDefault(p => p.ProductId == id);
           List<Comment> tt = _contaxt.Comments.Where(x=>x.ProductId == id).ToList();
            Seller seller = _contaxt.Sellers.FirstOrDefault(p=>p.SellerId == TargerProduct.SellerId);
            ExtraImage extra = _contaxt.ExtraImages.FirstOrDefault(p => p.ProductId == id);
            ViewData["ExtraImages"] = extra;
            ViewData["Seller"] = seller.CompanyName;
            ViewData["Comments"] = tt;
            ViewData["Contact"] = seller.Email;


            var user = HttpContext.User;
            var nameClaim = user.Claims.FirstOrDefault(c => c.Type == "UserID")?.Value;
            var userName = user.Claims.FirstOrDefault(c => c.Type == "Username")?.Value;

            if (nameClaim != null)
            {
                ViewBag.SignInStatus = true;
                ViewBag.Name = userName;
            }

            return View(TargerProduct);
        }
    }
}

Wild-Deer/Controllers/ShopController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Caching.Distributed;
using System.Text.Json;
using Wild_Deer.Models;

namespace Wild_Deer.Controllers
{
    [Authorize(Policy = "SignedInCustomer")]
    public class ShopController : Controller
    {

        private readonly IDistributedCache redis;
        public ShopController(IDistributedCache chache)
        {
            redis = chache;
        }



        public IActionResult Index()
        {
            //if redis is empty shop
            //else
            var user = HttpContext.User;
            var nameClaim = user.Claims.FirstOrDefault(c => c.Type == "UserID")?.Value;
            string key = "AddedProductsByID:" + nameClaim;
            var eq = redis.GetString(key);
            List<Product> products = new List<Product>();
            if (eq != null)
            {
                products = JsonSerializer.Deserialize<List<Product>>(redis.GetString(key));
                List<Product> send_these = new List<Product>();


                for (int i = 0; i < products.Count; i++)
                {
                    if (ViewData["ProductID" + products[i].ProductId] == null)
                    {
                        ViewData["ProductID" + products[i].ProductId] = products.Where(vvvvv => vvvvv.ProductId == products[i].ProductId).ToList().Count;
                        send_these.Add(products[i]);
                    }
                }

                return View(send_these);
            }
            else
            {
                return View(null);
            }

        }
        


        public IActionResult Plus(int productID)
        {
            var user = HttpContext.User;
            var nameClaim = user.Claims.FirstOrDefault(c => c.Type == "UserID")?.Value;
            string key = "AddedProductsByID:" + nameClaim;
            List<Product> products = new List<Product>();
            products = JsonSerializer.Deserialize<List<Product>>(redis.GetString(key));
            Product target = products.FirstOrDefault(x=>x.ProductId == productID);
            products.Add(target);
            redis.SetString(key, JsonSerializer.Serialize(products), new DistributedCacheEntryOptions
            {
                AbsoluteExpirationRelativeToNow = TimeSpan.FromDays(5)
            });
            return Redirect("Index");
        }
        public IActionResult Minus(int productID)
        {
            var user = HttpContext.User;
            var nameClaim = user.Claims.FirstOrDefault(c => c.Type == "UserID")?.Value;
            string key = "AddedProductsByID:" + nameClaim;
            List<Product> products = new List<Product>();
            products = JsonSerializer.Deserialize<List<Product>>(redis.GetString(key));
            Product target = products.FirstOrDefault(x => x.ProductId == productID);
            products.Remove(target);
            redis.SetString(key, JsonSerializer.Serialize(products), new DistributedCacheEntryOptions
            {
                AbsoluteExpirationRelativeToNow = TimeSpan.FromDays(5)
            });
            return Redirect("Index");
        }
    }
}

Wild-Deer/Views/Shared/Carts.cshtml
@model Product
<div class="card" style="width:250px;">
    <div class="row" alt="img row">
        <div class="col">
            <a asp-controller="Detail" asp-action="Detail" asp-route-id="@Model.ProductId"> <img src="@Model.Image" class="card-img-top" alt="Fissure in Sandstone" style="height:250px" /></a>
        </div>
    </div>

    <div class="row mt-3 mx-1" alt="title row">
        <div class="col"><h5 class="card-title text-lg-start">@Model.Title</h5></div>
    </div>

    <div class="row text-left mx-1" alt="description row">
        <div class="col"><p class="card-text text-lg-start" >@Model.Description</p></div>
    </div>


    <div class="row mt-3 mx-1 mb-2 text-lg-start" alt="price and shop button row">
        <div class="col text-lg-start">
            <form method="post">
                <button class="btn add btn-primary" asp-controller="Cache" asp-action="CachePlease" asp-route-ProductID="@Model.ProductId">Add</button>
            </form>
        </div>
        <div class="col mb-1 text-lg-end mt-2">
            <h5>@Model.Price $</h5>
        </div>
    </div>
</div>

Wild-Deer/Views/Shared/Footer.cshtml
<style>
    body {
    background: #fbfbfd;
}

.new_footer_area {
    background: #fbfbfd;
}


.new_footer_top {
    padding: 120px 0px 270px;
    position: relative;
      overflow-x: hidden;
}
.new_footer_area .footer_bottom {
    padding-top: 5px;
    padding-bottom: 50px;
}
.footer_bottom {
    font-size: 14px;
    font-weight: 300;
    line-height: 20px;
    color: #7f88a6;
    padding: 27px 0px;
}
.new_footer_top .company_widget p {
    font-size: 16px;
    font-weight: 300;
    line-height: 28px;
    color: #6a7695;
    margin-bottom: 20px;
}
.new_footer_top .company_widget .f_subscribe_two .btn_get {
    border-width: 1px;
    margin-top: 20px;
}
.btn_get_two:hover {
    background: transparent;
    color: #5e2ced;
}
.btn_get:hover {
    color: #fff;
    background: #6754e2;
    border-color: #6754e2;
    -webkit-box-shadow: none;
    box-shadow: none;
}
a:hover, a:focus, .btn:hover, .btn:focus, button:hover, button:focus {
    text-decoration: none;
    outline: none;
}



.new_footer_top .f_widget.about-widget .f_list li a:hover {
    color: #5e2ced;
}
.new_footer_top .f_widget.about-widget .f_list li {
    margin-bottom: 11px;
}
.f_widget.about-widget .f_list li:last-child {
    margin-bottom: 0px;
}
.f_widget.about-widget .f_list li {
    margin-bottom: 15px;
}
.f_widget.about-widget .f_list {
    margin-bottom: 0px;
}
.new_footer_top .f_social_icon a {
    width: 44px;
    height: 44px;
    line-height: 43px;
    background: transparent;
    border: 1px solid #e2e2eb;
    font-size: 24px;
}
.f_social_icon a {
    width: 46px;
    height: 46px;
    border-radius: 50%;
    font-size: 14px;
    line-height: 45px;
    color: #858da8;
    display: inline-block;
    background: #ebeef5;
    text-align: center;
    -webkit-transition: all 0.2s linear;
    -o-transition: all 0.2s linear;
    transition: all 0.2s linear;
}
.ti-facebook:before {
    content: "\e741";
}
.ti-twitter-alt:before {
    content: "\e74b";
}
.ti-vimeo-alt:before {
    content: "\e74a";
}
.ti-pinterest:before {
    content: "\e731";
}

.btn_get_two {
    -webkit-box-shadow: none;
    box-shadow: none;
    background: #5e2ced;
    border-color: #5e2ced;
    color: #fff;
}

.btn_get_two:hover {
    background: transparent;
    color: #5e2ced;
}

.new_footer_top .f_social_icon a:hover {
    background: #5e2ced;
    border-color: #5e2ced;
  color:white;
}
.new_footer_top .f_social_icon a + a {
    margin-left: 4px;
}
.new_footer_top .f-title {
    margin-bottom: 30px;
    color: #263b5e;
}
.f_600 {
    font-weight: 600;
}
.f_size_18 {
    font-size: 18px;
}
h1, h2, h3, h4, h5, h6 {
    color: #4b505e;
}
.new_footer_top .f_widget.about-widget .f_list li a {
    color: #6a7695;
}


.new_footer_top .footer_bg {
    position: absolute;
    bottom: 0;
    background: url("https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEigB8iI5tb8WSVBuVUGc9UjjB8O0708X7Fdic_4O1LT4CmLHoiwhanLXiRhe82yw0R7LgACQ2IhZaTY0hhmGi0gYp_Ynb49CVzfmXtYHUVKgXXpWvJ_oYT8cB4vzsnJLe3iCwuzj-w6PeYq_JaHmy_CoGoa6nw0FBo-2xLdOPvsLTh_fmYH2xhkaZ-OGQ/s16000/footer_bg.png") no-repeat scroll center 0;
    width: 100%;
    height: 266px;
}

.new_footer_top .footer_bg .footer_bg_one {
    background: url("https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEia0PYPxwT5ifToyP3SNZeQWfJEWrUENYA5IXM6sN5vLwAKvaJS1pQVu8mOFFUa_ET4JuHNTFAxKURFerJYHDUWXLXl1vDofYXuij45JZelYOjEFoCOn7E6Vxu0fwV7ACPzArcno1rYuVxGB7JY6G7__e4_KZW4lTYIaHSLVaVLzklZBLZnQw047oq5-Q/s16000/volks.gif") no-repeat center center;
    width: 330px;
    height: 105px;
  background-size:100%;
    position: absolute;
    bottom: 0;
    left: 30%;
    -webkit-animation: myfirst 22s linear infinite;
    animation: myfirst 22s linear infinite;
}

.new_footer_top .footer_bg .footer_bg_two {
    background: url("https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhyLGwEUVwPK6Vi8xXMymsc-ZXVwLWyXhogZxbcXQYSY55REw_0D4VTQnsVzCrL7nsyjd0P7RVOI5NKJbQ75koZIalD8mqbMquP20fL3DxsWngKkOLOzoOf9sMuxlbyfkIBTsDw5WFUj-YJiI50yzgVjF8cZPHhEjkOP_PRTQXDHEq8AyWpBiJdN9SfQA/s16000/cyclist.gif") no-repeat center center;
    width: 88px;
    height: 100px;
  background-size:100%;
    bottom: 0;
    left: 38%;
    position: absolute;
    -webkit-animation: myfirst 30s linear infinite;
    animation: myfirst 30s linear infinite;
}



-moz-keyframes myfirst {
  0% {
    left: -25%;
  }
  100% {
    left: 100%;
  }
}

-webkit-keyframes myfirst {
  0% {
    left: -25%;
  }
  100% {
    left: 100%;
  }
}

keyframes myfirst {
  0% {
    left: -25%;
  }
  100% {
    left: 100%;
  }
}

</style>

    <footer class="new_footer_area bg_color">
        <div class="new_footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="f_widget company_widget wow fadeInLeft" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeInLeft;">
                            <h3 class="f-title f_600 t_color f_size_18">Get in Touch</h3>
                            <form action="#" class="f_subscribe_two mailchimp" method="post" novalidate="true" _lpchecked="1">
                                <input type="text" name="EMAIL" class="form-control memail" placeholder="Email">
                                <button class="btn btn_get btn_get_two" type="submit">Subscribe</button>
                                <p class="mchimp-errmessage" style="display: none;"></p>
                                <p class="mchimp-sucmessage" style="display: none;"></p>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="f_widget about-widget pl_70 wow fadeInLeft" data-wow-delay="0.4s" style="visibility: visible; animation-delay: 0.4s; animation-name: fadeInLeft;">
                            <h3 class="f-title f_600 t_color f_size_18">Cnatact Us</h3>
                            <ul class="list-unstyled f_list mx-3">
                            <li><a href="https://t.me/ali_a02i"><img src="~/img/Telegram.png" height="40px"></img></a></li>
                            <li><a href=""><img src="~/img/Instagram.png" height="40"></img></a></li>
                            <li><a href="https://github.com/Ali-Ahmadii"><img src="~/img/Github.png" height="40"></img></a></li>
                            <li><a href="https://www.linkedin.com/in/ali-ahmadi-199855280/"><img src="~/img/Linkedin.png" height="40"></img></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="f_widget about-widget pl_70 wow fadeInLeft" data-wow-delay="0.6s" style="visibility: visible; animation-delay: 0.6s; animation-name: fadeInLeft;">
                            <h3 class="f-title f_600 t_color f_size_18">Help</h3>
                            <ul class="list-unstyled f_list">
                                <li><a href="#">FAQ</a></li>
                                <li><a href="#">Term &amp; conditions</a></li>
                                <li><a href="#">Reporting</a></li>
                                <li><a href="#">Documentation</a></li>
                                <li><a href="#">Support Policy</a></li>
                                <li><a href="#">Privacy</a></li>
                            </ul>
                        </div>
                    </div>
                <div class="col-lg-3 col-md-6 t_color f-title">
                        <p>This SIte Has Been Made By Me Ali Ahmadi</p>
                        <br />
                        <p>Wish You Bests</p>
                    </div>
                </div>
            </div>
            <div class="footer_bg">
                <div class="footer_bg_one"></div>
                <div class="footer_bg_two"></div>
            </div>
        </div>
        <div class="footer_bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-sm-7">
                        <p class="mb-0 f_400">© Ali Ahmadi 2024 All rights reserved.</p>
                    </div>
                    <div class="col-lg-6 col-sm-5 text-right">
                    <p> <i class="icon_heart"></i> <a href="https://github.com/Ali-Ahmadii" target="_blank">Ali Ahmadi</a></p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</section></html>

Wild-Deer/Views/Shared/SlideShow.cshtml
<style>

    .carousel-item {
        height: 400px; /* Adjust the height as needed */
    }

    .carousel-img {
        object-fit: cover;
        height: 100%;
        width: 100%;
    }

</style>
<script>
    var myIndex = 0;
    carousel();

    function carousel() {
        var i;
        var x = document.getElementsByClassName("mySlides");
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "blcok";
        }
        myIndex++;
        if (myIndex > x.length) { myIndex = 1 }
        x[myIndex - 1].style.display = "block";
        setTimeout(carousel, 5000);
    }
</script>
<section>
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="@ViewData["IMG1"]" class="carousel-img d-block w-100" alt="Slide 1">
            </div>
            <div class="carousel-item">
                <img src="@ViewData["IMG2"]" class="carousel-img d-block w-100" alt="Slide 2">
            </div>
            <div class="carousel-item">
                <img src="@ViewData["IMG3"]" class="carousel-img d-block w-100" alt="Slide 2">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</section>

Wild-Deer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Basha_Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/blur.css" />
    <link rel="stylesheet" href="~/Basha_Shop.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
    <partial name="topbar" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <partial name="Footer" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Wild-Deer/Views/Shared/topbar.cshtml
<style>
    /* Style the dropdown menu */
    .dropdown-menu {
        background-color: #232F3E;
    }

    .dropdown-item {
        color: #fff;
    }

        .dropdown-item:hover {
            background-color: #43519B;
        }

</style>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand"  asp-controller="Home" asp-action="Index">
            <img src="~/img/logo.png" alt="Basha Shop" width="75" height="60"></img>
        </a>
        <form class="d-flex flex-grow-1 ms-auto">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                @{
                        string name = ViewBag.Name != null ? ViewBag.Name : null;
                }
                <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" asp-controller="Account" asp-action="Index"  id="accountDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Hello @name
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="accountDropdown">
                            @{
                                if(ViewBag.SignInStatus == true)
                                {
                                    if (ViewBag.Role == "Customer")
                                    {
                                        <li><a class="dropdown-item" asp-controller="CustomerProfile" asp-action="Index">Your Account</a></li>
                                        <li><a class="dropdown-item" asp-controller="Account" asp-action="SignOut">Sign Out</a></li>
                                    }
                                    if (ViewBag.Role == "Seller")
                                    {
                                        <li><a class="dropdown-item" asp-controller="SellerProfile" asp-action="Index">Your Account</a></li>
                                        <li><a class="dropdown-item" asp-controller="Account" asp-action="SignOut">Sign Out</a></li>
                                    }
                                }
                                else
                                {
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="Signin">Sign In</a></li>
                                }
                            }

                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Shop" asp-action="Index"><i class="fas fa-cart-plus"></i> Cart</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>